### ISSUE TITLE
Add help message and env variable defaults

### ISSUE THREAD

**Issue by ropottnik** [Jeremy-Stafford/datacli#2]
Hey there! 

Nice and lean lib for creating CLI arguments from a dataclass!

I'd like to add the options to let fields default to environment variables, add help text and include the env variable in _help_ and error messages for missing parameters. 

In fact, I have already done it so the question is more, would a PR be appreciated ;-)

**Comment by Jeremy-Stafford** [comment]
Go ahead, I'll give it a review as soon as possible.
